###一个 post请求，body一定要是json 的格式###
Post {{host}}/api/home/login
Content-Type: application/json;charset=UTF-8

{
    "userName":"15000000000",
    "password":"admin"
}

###
GET {{host}}/v1?token={{token}} HTTP/1.1


### 
GET https://api.jsonbin.io/v3/b/617607c2aa02be1d445e555c/4
X-Master-Key:$2b$10$37ieP2eGcWGXJ3Odycu87O.mKLmDBB4oQQp.QvP9xdzFOKu7peQQ.
Content-Type: application/json;charset=UTF-8